name: Test działania, wysłanie do DockerHub
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Budowa obrazu
        run: docker build -t mkvskyx/stock-analyzer-bot --build-arg="BOT_TOKEN=${{ secrets.BOT_TOKEN }}" .
      - name: Test działania
        run: docker run -e CI=true -d mkvskyx/stock-analyzer-bot
      - name: Logowanie do DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Wysłanie obrazu do DockerHub
        run: docker push mkvskyx/stock-analyzer-bot